### ISSUE TITLE
osdev/cpp YouTube channels

### ISSUE THREAD

**Issue by cristian-programmer** [skiftOS/skift-cpp#1]
https://www.youtube.com/watch?v=1rnA6wpF0o4&list=PLHh55M_Kq4OApWScZyPl5HhgsTJS9MZ6M

I don't know if you already know them, but I leave you the link, the author of the videos writes a kernel in c ++ and makes good use of object-oriented programming.

**Comment by NicolasVanBossuyt** [comment]
Yes y know about it, you should checkout Andreas Kling on YouTube to ;) 

PS: if you want just to talk with me comme joint me on discord through the skiftOS discord server ;)

**Comment by cristian-programmer** [comment]
yes, great, would you give me the url? from the discord channel

**Comment by NicolasVanBossuyt** [comment]
The [discord server](https://discord.gg/gamGsfg) ;)
